# -*- coding: utf-8 -*-
"""Project UAS Prostok

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORaT9TLeQBi0lGg-e-hC31snU_nav9cS
"""

import numpy as np
import pandas as pd
import random

random.seed(123)
np.random.seed(123)

class MarkovChain:

    def __init__(self, states, transition_matrix):

        self.states = states
        self.transition_matrix = np.array(transition_matrix)
        self.num_states = len(states)

        if self.transition_matrix.shape != (self.num_states, self.num_states):
            raise ValueError("Ukuran matriks tidak sesuai.")

        if not np.allclose(self.transition_matrix.sum(axis=1), 1):
            raise ValueError("Jumlah probabilitas setiap baris harus 1.")

        self.state_to_index = {
            state: i for i, state in enumerate(states)
        }

        self.index_to_state = {
            i: state for i, state in enumerate(states)
        }

    # ==================================================
    # MENENTUKAN STATE BERIKUTNYA
    # ==================================================

    def get_next_state(self, current_state):

        idx = self.state_to_index[current_state]

        next_idx = random.choices(
            range(self.num_states),
            weights=self.transition_matrix[idx],
            k=1
        )[0]

        return self.index_to_state[next_idx]

    # ==================================================
    # SIMULASI SATU PASIEN
    # ==================================================

    def simulate(self, initial_state, num_steps):

        current_state = initial_state

        history = [current_state]

        for step in range(num_steps):

            current_state = self.get_next_state(current_state)

            history.append(current_state)

            if current_state == "Meninggal":
                break

        return history

    # ==================================================
    # PROBABILITAS TIAP HARI
    # ==================================================

    def probability_table(self, initial_state, num_steps):

        initial_vector = np.zeros(self.num_states)

        initial_vector[
            self.state_to_index[initial_state]
        ] = 1

        current_prob = initial_vector

        results = []

        for day in range(num_steps + 1):

            row = {"Hari": day}

            for state, prob in zip(
                self.states,
                current_prob
            ):
                row[state] = round(prob, 4)

            results.append(row)

            current_prob = (
                current_prob @ self.transition_matrix
            )

        return pd.DataFrame(results)

    # ==================================================
    # DISTRIBUSI JANGKA PANJANG
    # ==================================================

    def steady_state(self, initial_state, n=100):

        initial_vector = np.zeros(self.num_states)

        initial_vector[
            self.state_to_index[initial_state]
        ] = 1

        Pn = np.linalg.matrix_power(
            self.transition_matrix,
            n
        )

        steady = initial_vector @ Pn

        return dict(zip(self.states, steady))

    # ==================================================
    # SIMULASI BANYAK PASIEN
    # ==================================================

    def simulate_many_patients(
        self,
        initial_state,
        num_steps,
        num_patients=100
    ):

        final_states = []

        for _ in range(num_patients):

            history = self.simulate(
                initial_state,
                num_steps
            )

            final_states.append(
                history[-1]
            )

        result = (
            pd.Series(final_states)
            .value_counts(normalize=True)
            .sort_index()
        )

        return result


# ==================================================
# STATE KONDISI PASIEN
# ==================================================

states = [
    "Sehat",
    "Sakit Ringan",
    "Sakit Berat",
    "Meninggal"
]

# ==================================================
# MATRIKS TRANSISI
# ==================================================

transition_matrix = [

    # Sehat
    [0.85, 0.10, 0.04, 0.01],

    # Sakit Ringan
    [0.50, 0.30, 0.15, 0.05],

    # Sakit Berat
    [0.10, 0.25, 0.40, 0.25],

    # Meninggal (absorbing state)
    [0.00, 0.00, 0.00, 1.00]
]

# ==================================================
# MEMBUAT MODEL
# ==================================================

mc = MarkovChain(
    states,
    transition_matrix
)

# ==================================================
# SIMULASI 1 PASIEN
# ==================================================

print("\n=== SIMULASI SATU PASIEN ===")

history = mc.simulate(
    initial_state="Sehat",
    num_steps=10
)

for day, state in enumerate(history):
    print(f"Hari ke-{day}: {state}")

# ==================================================
# TABEL PROBABILITAS
# ==================================================

print("\n=== TABEL PROBABILITAS ===")

df_prob = mc.probability_table(
    initial_state="Sehat",
    num_steps=10
)

print(df_prob)

# ==================================================
# DISTRIBUSI JANGKA PANJANG
# ==================================================

print("\n=== DISTRIBUSI JANGKA PANJANG ===")

steady = mc.steady_state(
    initial_state="Sehat",
    n=100
)

for state, prob in steady.items():
    print(f"{state:<15}: {prob:.4f}")